Vagrant.configure("2") do |config|
	config.vm.box = "centos/7"
	config.vm.box_check_update = true
	config.vm.post_up_message = "Vagrant box up - connect with 'vagrant ssh'"
	config.vm.synced_folder ".", "/vagrant", type: "virtualbox", disabled: true

	config.vm.provider "virtualbox" do |v|
		v.name = "centos-test"
  		v.gui = false
		v.memory = 1024
		v.cpus = 1
	end   
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "play.yml"
    end  
end