Vagrant.require_version ">= 1.9.1"

servers = {
    :etcd => [ 
        { :name => "etcd01", :ip => "192.168.10.4" },{ :name => "etcd02", :ip => "192.168.10.5" }
    ]
}

Vagrant.configure("2") do |config|
    etcd_index = 0
    servers[:etcd].each do |etcd_srv|
        etcd_index += 1
        config.vm.define "#{etcd_srv[:name]}" do |d|
            d.vm.box = "centos/7"
            d.vm.hostname = "#{etcd_srv[:name]}"
            d.vm.synced_folder ".", "/vagrant", type: "virtualbox", disabled: true
            d.vm.network "private_network", ip: "#{etcd_srv[:ip]}"
            
            d.vm.provider "virtualbox" do |v|
				v.name = "#{etcd_srv[:name]}"
				v.gui = false
				v.memory = 256
				v.cpus = 1
            end
            
            d.vm.provision "shell", 
                env: { "ETCD_CL_NAME" => "etcd-cluster" },
                inline: <<-SHELL
                    yum install -y epel-release yum-utils \
                        device-mapper-persistent-data \
                        lvm2

                    yum-config-manager \
                        --add-repo \
                        https://download.docker.com/linux/centos/docker-ce.repo

                    yum install -y docker-ce ntp jq

                    systemctl enable ntpd
                    systemctl start ntpd

                    [ ! -d /etc/docker ] && mkdir /etc/docker
                    echo "{}" | jq '."exec-opts" |= .+ ["native.cgroupdriver=systemd"]' > /etc/docker/daemon.json

                    systemctl restart docker.service
                SHELL
        end
    end
end