load 'config.rb'

count = 0

SERVERS.each do |server|
        if count < AWS[:vpc][:subnets].length
        then
                puts AWS[:vpc][:subnets][count][:id]
                count = count + 1
        else
                count = 0
                puts AWS[:vpc][:subnets][count][:id]
        end
end

