---

- name: test
  hosts: etcd 
  tasks:
    - debug:
        msg: "{% for server in groups['etcd'] %}{{ hostvars[server]['ip'] }}{% if loop.index < groups['etcd']|length %},{% endif %}{% endfor %}"
